name: elgato

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dcli: ^0.50.0
  http: ^0.13.0
  # version 0.3.0 isn't released yet.
  # See https://github.com/flutter/packages/pull/297
  multicast_dns:
    git:
      url: https://github.com/flutter/packages.git
      path: packages/multicast_dns
      ref: d83cd11631650c2972401c065a8a64b55e0ab754
